package exercicio2;
/**
 *
 * @author Davi Ricardo
 */
public class JFrameConversorMonetario extends javax.swing.JFrame {
    boolean radioDolar, radioIene, radioWon = false;
    /**
     * Creates new form JFrameConversorMonetario
     */
    public JFrameConversorMonetario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jRadioDolar = new javax.swing.JRadioButton();
        jRadioIene = new javax.swing.JRadioButton();
        jRadioWon = new javax.swing.JRadioButton();
        jLabelResultado = new javax.swing.JLabel();
        jButtonConverter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Real Brasileiro (BRL)");
        jLabel1.setToolTipText("");

        buttonGroup1.add(jRadioDolar);
        jRadioDolar.setText("Dólar Americano (USD)");
        jRadioDolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioDolarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioIene);
        jRadioIene.setText("Iene japonês (JPY/円)");
        jRadioIene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioIeneActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioWon);
        jRadioWon.setText("Won sul-coreano (KRW원)");
        jRadioWon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioWonActionPerformed(evt);
            }
        });

        jLabelResultado.setToolTipText("");
        jLabelResultado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonConverter.setText("Converter");
        jButtonConverter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConverterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioDolar)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioIene))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jRadioWon)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonConverter)
                    .addComponent(jLabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioDolar)
                    .addComponent(jRadioIene))
                .addGap(18, 18, 18)
                .addComponent(jRadioWon)
                .addGap(27, 27, 27)
                .addComponent(jLabelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButtonConverter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioDolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioDolarActionPerformed
        radioDolar = true;
        radioIene = false;
        radioWon = false;
    }//GEN-LAST:event_jRadioDolarActionPerformed

    private void jRadioIeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioIeneActionPerformed
        radioIene = true;
        radioDolar = false;
        radioWon = false;
    }//GEN-LAST:event_jRadioIeneActionPerformed

    private void jRadioWonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioWonActionPerformed
        radioWon = true;
        radioDolar = false;
        radioIene = false;
    }//GEN-LAST:event_jRadioWonActionPerformed

    private void jButtonConverterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConverterActionPerformed
        float valorReais = Float.parseFloat(jTextField1.getText());
        String valorConversao;
        
        if (radioDolar) {
            valorConversao = Double.toString(valorReais * 0.20);
        } else if (radioIene) {
            valorConversao = Double.toString(valorReais * 27.11);
        } else {
            valorConversao = Double.toString(valorReais * 265.74);
        }
        jLabelResultado.setText(valorConversao);
    }//GEN-LAST:event_jButtonConverterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameConversorMonetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameConversorMonetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameConversorMonetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameConversorMonetario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameConversorMonetario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonConverter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JRadioButton jRadioDolar;
    private javax.swing.JRadioButton jRadioIene;
    private javax.swing.JRadioButton jRadioWon;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
