package exercicio1;

public class JFrameCalculadora extends javax.swing.JFrame {
    String text1 = ""; 
    String text2 = "";
    String text3 = "";
    String resultado = "";
    char operacao = ' ';
    int contSoma, contSubt, contMult, contDivi, contPonto = 0;
    float num1, num2;
    /**
     * Creates new form NewJFrame
     */
    public JFrameCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonDividir = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButtonMultiplicar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButtonSubtrair = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonPonto = new javax.swing.JButton();
        jButtonIgualdade = new javax.swing.JButton();
        jButtonSomar = new javax.swing.JButton();
        jTextField = new javax.swing.JTextField();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jScrollPane1.setViewportView(jTree1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButtonDividir.setText("/");
        jButtonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDividirActionPerformed(evt);
            }
        });

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("5");
        jButton5.setToolTipText("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButtonMultiplicar.setText("*");
        jButtonMultiplicar.setToolTipText("");
        jButtonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicarActionPerformed(evt);
            }
        });

        jButton1.setText("1");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("2");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButtonSubtrair.setText("-");
        jButtonSubtrair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubtrairActionPerformed(evt);
            }
        });

        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButtonPonto.setText(".");
        jButtonPonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPontoActionPerformed(evt);
            }
        });

        jButtonIgualdade.setText("=");
        jButtonIgualdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualdadeActionPerformed(evt);
            }
        });

        jButtonSomar.setText("+");
        jButtonSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSomarActionPerformed(evt);
            }
        });

        jTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonIgualdade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButtonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSubtrair, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIgualdade, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSomar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (operacao == ' ') {
           text1 = text1 + "8";
           jTextField.setText(text1); 
        } else if ("".equals(resultado)) {
           text2 = text2 + "8";
           jTextField.setText(text1 + " " + operacao + " " + text2);
        } else {
           text3 = text3 + "8";
           jTextField.setText(resultado + " " + operacao + " " + text3);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (operacao == ' ') {
           text1 = text1 + "4";
           jTextField.setText(text1); 
        } else if ("".equals(resultado)) {
           text2 = text2 + "4";
           jTextField.setText(text1 + " " + operacao + " " + text2);
        } else {
           text3 = text3 + "4";
           jTextField.setText(resultado + " " + operacao + " " + text3);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (operacao == ' ') {
           text1 = text1 + "7";
           jTextField.setText(text1); 
        } else if ("".equals(resultado)) {
           text2 = text2 + "7";
           jTextField.setText(text1 + " " + operacao + " " + text2);
        } else {
           text3 = text3 + "7";
           jTextField.setText(resultado + " " + operacao + " " + text3);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButtonSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSomarActionPerformed
        switch (operacao) {
            case '-' -> {
               operacao = '+';
               if ("".equals(resultado)) {
                    num1 = Float.parseFloat(text1);
                    num2 = Float.parseFloat(text2);
                    resultado = Float.toString(num1 - num2);
                    jTextField.setText(resultado + " " + operacao + " ");
                } else {
                    num1 = Float.parseFloat(resultado);
                    num2 = Float.parseFloat(text3);
                    resultado = Float.toString(num1 - num2);
                    text3 = "";
                    jTextField.setText(resultado + " " + operacao + " ");
                }
            }          
            case '*' -> {
               operacao = '+';
               if ("".equals(resultado)) {
                    num1 = Float.parseFloat(text1);
                    num2 = Float.parseFloat(text2);
                    resultado = Float.toString(num1 * num2);
                    jTextField.setText(resultado + " " + operacao + " ");
                } else {
                    num1 = Float.parseFloat(resultado);
                    num2 = Float.parseFloat(text3);
                    resultado = Float.toString(num1 * num2);
                    text3 = "";
                    jTextField.setText(resultado + " " + operacao + " ");
                }
            }
            case '/' -> {
                operacao = '+';
               if ("".equals(resultado)) {
                    num1 = Float.parseFloat(text1);
                    num2 = Float.parseFloat(text2);
                    resultado = Float.toString(num1 / num2);
                    jTextField.setText(resultado + " " + operacao + " ");
                } else {
                    num1 = Float.parseFloat(resultado);
                    num2 = Float.parseFloat(text3);
                    resultado = Float.toString(num1 / num2);
                    text3 = "";
                    jTextField.setText(resultado + " " + operacao + " ");
                }
            }
            default -> {
                operacao = '+';
                if (contSoma == 0 && "".equals(text2)) {
                    jTextField.setText(text1 + " + ");      
                } else if (contSoma == 1 && "".equals(resultado)) {
                    num1 = Float.parseFloat(text1);
                    num2 = Float.parseFloat(text2);
                    resultado = Float.toString(num1 + num2);
                    jTextField.setText(resultado + " " + operacao + " ");
                } else {
                    num1 = Float.parseFloat(resultado);
                    num2 = Float.parseFloat(text3);
                    text3 = "";
                    resultado = Float.toString(num1 + num2);
                    jTextField.setText(resultado + " " + operacao + " ");
                } 
            }
        }
        contSoma++;
    }//GEN-LAST:event_jButtonSomarActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (operacao == ' ') {
           text1 = text1 + "9";
           jTextField.setText(text1); 
        } else if ("".equals(resultado)) {
           text2 = text2 + "9";
           jTextField.setText(text1 + " " + operacao + " " + text2);
        } else {
           text3 = text3 + "9";
           jTextField.setText(resultado + " " + operacao + " " + text3);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (operacao == ' ') {
           text1 = text1 + "5";
           jTextField.setText(text1); 
        } else if ("".equals(resultado)) {
           text2 = text2 + "5";
           jTextField.setText(text1 + " " + operacao + " " + text2);
        } else {
           text3 = text3 + "5";
           jTextField.setText(resultado + " " + operacao + " " + text3);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (operacao == ' ') {
           text1 = text1 + "6";
           jTextField.setText(text1); 
        } else if ("".equals(resultado)) {
           text2 = text2 + "6";
           jTextField.setText(text1 + " " + operacao + " " + text2);
        } else {
           text3 = text3 + "6";
           jTextField.setText(resultado + " " + operacao + " " + text3);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (operacao == ' ') {
           text1 = text1 + "1";
           jTextField.setText(text1); 
        } else if ("".equals(resultado)) {
           text2 = text2 + "1";
           jTextField.setText(text1 + " " + operacao + " " + text2);
        } else {
           text3 = text3 + "1";
           jTextField.setText(resultado + " " + operacao + " " + text3);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (operacao == ' ') {
           text1 = text1 + "2";
           jTextField.setText(text1); 
        } else if ("".equals(resultado)) {
           text2 = text2 + "2";
           jTextField.setText(text1 + " " + operacao + " " + text2);
        } else {
           text3 = text3 + "2";
           jTextField.setText(resultado + " " + operacao + " " + text3);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (operacao == ' ') {
           text1 = text1 + "3";
           jTextField.setText(text1); 
        } else if ("".equals(resultado)) {
           text2 = text2 + "3";
           jTextField.setText(text1 + " " + operacao + " " + text2);
        } else {
           text3 = text3 + "3";
           jTextField.setText(resultado + " " + operacao + " " + text3);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        if (operacao == ' ') {
           text1 = text1 + "0";
           jTextField.setText(text1); 
        } else if ("".equals(resultado)) {
           text2 = text2 + "0";
           jTextField.setText(text1 + " " + operacao + " " + text2);
        } else {
           text3 = text3 + "0";
           jTextField.setText(resultado + " " + operacao + " " + text3);
        }
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDividirActionPerformed
        switch (operacao) {
            case '-' -> {
               operacao = '/';
               if ("".equals(resultado)) {
                    num1 = Float.parseFloat(text1);
                    num2 = Float.parseFloat(text2);
                    resultado = Float.toString(num1 - num2);
                    jTextField.setText(resultado + " " + operacao + " ");
                } else {
                    num1 = Float.parseFloat(resultado);
                    num2 = Float.parseFloat(text3);
                    resultado = Float.toString(num1 - num2);
                    text3 = "";
                    jTextField.setText(resultado + " " + operacao + " ");
                }
            }          
            case '*' -> {
               operacao = '/';
               if ("".equals(resultado)) {
                    num1 = Float.parseFloat(text1);
                    num2 = Float.parseFloat(text2);
                    resultado = Float.toString(num1 * num2);
                    jTextField.setText(resultado + " " + operacao + " ");
                } else {
                    num1 = Float.parseFloat(resultado);
                    num2 = Float.parseFloat(text3);
                    resultado = Float.toString(num1 * num2);
                    text3 = "";
                    jTextField.setText(resultado + " " + operacao + " ");
                }
            }
            case '+' -> {
                operacao = '/';
               if ("".equals(resultado)) {
                    num1 = Float.parseFloat(text1);
                    num2 = Float.parseFloat(text2);
                    resultado = Float.toString(num1 + num2);
                    jTextField.setText(resultado + " " + operacao + " ");
                } else {
                    num1 = Float.parseFloat(resultado);
                    num2 = Float.parseFloat(text3);
                    resultado = Float.toString(num1 + num2);
                    text3 = "";
                    jTextField.setText(resultado + " " + operacao + " ");
                }
            }
            default -> {
                operacao = '/';
                if (contSoma == 0 && "".equals(text2)) {
                    jTextField.setText(text1 + " / ");      
                } else if (contSoma == 1 && "".equals(resultado)) {
                    num1 = Float.parseFloat(text1);
                    num2 = Float.parseFloat(text2);
                    resultado = Float.toString(num1 / num2);
                    jTextField.setText(resultado + " " + operacao + " ");
                } else {
                    num1 = Float.parseFloat(resultado);
                    num2 = Float.parseFloat(text3);
                    text3 = "";
                    resultado = Float.toString(num1 / num2);
                    jTextField.setText(resultado + " " + operacao + " ");
                } 
            }
        }
        contDivi++;
    }//GEN-LAST:event_jButtonDividirActionPerformed

    private void jButtonPontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPontoActionPerformed
        if (operacao == ' ') {
           text1 = text1 + ".";
           jTextField.setText(text1); 
        } else if ("".equals(resultado)) {
           text2 = text2 + ".";
           jTextField.setText(text1 + " " + operacao + " " + text2);
        } else {
           text3 = text3 + ".";
           jTextField.setText(resultado + " " + operacao + " " + text3);
        }
    }//GEN-LAST:event_jButtonPontoActionPerformed

    private void jTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldActionPerformed
     
    }//GEN-LAST:event_jTextFieldActionPerformed

    private void jButtonIgualdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualdadeActionPerformed
        num1 = Float.parseFloat(text1);
        num2 = Float.parseFloat(text2);
        
        switch (operacao) {
            case '+' -> {
                if (contSoma == 1) {
                    resultado = Float.toString(num1 + num2);
                    jTextField.setText(resultado);
                } else {
                    jTextField.setText(resultado);
                }                 
            }
            case '-' -> {
                if (contSubt == 1) {
                    resultado = Float.toString(num1 - num2);
                    jTextField.setText(resultado);
                } else {
                    jTextField.setText(resultado);
                }
            }
            case '*' -> {
                if (contMult == 1) {
                    resultado = Float.toString(num1 * num2);
                    jTextField.setText(resultado);
                } else {
                    jTextField.setText(resultado);
                }
            }
            case '/' -> {
                if (contDivi == 1) {
                    resultado = Float.toString(num1 / num2);
                    jTextField.setText(resultado);
                } else {
                    jTextField.setText(resultado);
                }
            }
            default -> {
                
            }
        }
        limparVariaveis();
    }//GEN-LAST:event_jButtonIgualdadeActionPerformed

    private void jButtonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicarActionPerformed
        switch (operacao) {
            case '-' -> {
               operacao = '*';
               if ("".equals(resultado)) {
                    num1 = Float.parseFloat(text1);
                    num2 = Float.parseFloat(text2);
                    resultado = Float.toString(num1 - num2);
                    jTextField.setText(resultado + " " + operacao + " ");
                } else {
                    num1 = Float.parseFloat(resultado);
                    num2 = Float.parseFloat(text3);
                    resultado = Float.toString(num1 - num2);
                    text3 = "";
                    jTextField.setText(resultado + " " + operacao + " ");
                }
            }          
            case '+' -> {
               operacao = '*';
               if ("".equals(resultado)) {
                    num1 = Float.parseFloat(text1);
                    num2 = Float.parseFloat(text2);
                    resultado = Float.toString(num1 + num2);
                    jTextField.setText(resultado + " " + operacao + " ");
                } else {
                    num1 = Float.parseFloat(resultado);
                    num2 = Float.parseFloat(text3);
                    resultado = Float.toString(num1 + num2);
                    text3 = "";
                    jTextField.setText(resultado + " " + operacao + " ");
                }
            }
            case '/' -> {
                operacao = '*';
               if ("".equals(resultado)) {
                    num1 = Float.parseFloat(text1);
                    num2 = Float.parseFloat(text2);
                    resultado = Float.toString(num1 / num2);
                    jTextField.setText(resultado + " " + operacao + " ");
                } else {
                    num1 = Float.parseFloat(resultado);
                    num2 = Float.parseFloat(text3);
                    resultado = Float.toString(num1 / num2);
                    text3 = "";
                    jTextField.setText(resultado + " " + operacao + " ");
                }
            }
            default -> {
                operacao = '*';
                if (contSoma == 0 && "".equals(text2)) {
                    jTextField.setText(text1 + " * ");      
                } else if (contSoma == 1 && "".equals(resultado)) {
                    num1 = Float.parseFloat(text1);
                    num2 = Float.parseFloat(text2);
                    resultado = Float.toString(num1 * num2);
                    jTextField.setText(resultado + " " + operacao + " ");
                } else {
                    num1 = Float.parseFloat(resultado);
                    num2 = Float.parseFloat(text3);
                    text3 = "";
                    resultado = Float.toString(num1 * num2);
                    jTextField.setText(resultado + " " + operacao + " ");
                } 
            }
        }
        contMult++;
    }//GEN-LAST:event_jButtonMultiplicarActionPerformed

    private void jButtonSubtrairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubtrairActionPerformed
        switch (operacao) {
            case '+' -> {
                operacao = '-';
                if ("".equals(resultado)) {
                    num1 = Float.parseFloat(text1);
                    num2 = Float.parseFloat(text2);
                    resultado = Float.toString(num1 + num2);
                    jTextField.setText(resultado + " " + operacao + " ");
                } else {
                    num1 = Float.parseFloat(resultado);
                    num2 = Float.parseFloat(text3);
                    resultado = Float.toString(num1 + num2);
                    text3 = "";
                    jTextField.setText(resultado + " " + operacao + " ");
                }
            }          
            case '*' -> {
                operacao = '-';
                if ("".equals(resultado)) {
                    num1 = Float.parseFloat(text1);
                    num2 = Float.parseFloat(text2);
                    resultado = Float.toString(num1 * num2);
                    jTextField.setText(resultado + " " + operacao + " ");
                } else {
                    num1 = Float.parseFloat(resultado);
                    num2 = Float.parseFloat(text3);
                    resultado = Float.toString(num1 * num2);
                    text3 = "";
                    jTextField.setText(resultado + " " + operacao + " ");
                }
            }
            case '/' -> {
                operacao = '-';
                if ("".equals(resultado)) {
                    num1 = Float.parseFloat(text1);
                    num2 = Float.parseFloat(text2);
                    resultado = Float.toString(num1 / num2);
                    jTextField.setText(resultado + " " + operacao + " ");
                } else {
                    num1 = Float.parseFloat(resultado);
                    num2 = Float.parseFloat(text3);
                    resultado = Float.toString(num1 / num2);
                    text3 = "";
                    jTextField.setText(resultado + " " + operacao + " ");
                }
            }
            default -> {
                operacao = '-';
                if (contSubt == 0 && "".equals(text2)) {
                    jTextField.setText(text1 + " - ");      
                } else if (contSubt == 1 && "".equals(resultado)) {
                    num1 = Float.parseFloat(text1);
                    num2 = Float.parseFloat(text2);
                    resultado = Float.toString(num1 - num2);
                    jTextField.setText(resultado + " " + operacao + " ");
                } else {
                    num1 = Float.parseFloat(resultado);
                    num2 = Float.parseFloat(text3);
                    text3 = "";
                    resultado = Float.toString(num1 - num2);
                    jTextField.setText(resultado + " " + operacao + " ");
                } 
            }
        }
        contSubt++;
    }//GEN-LAST:event_jButtonSubtrairActionPerformed

    private void limparVariaveis () {
        text1 = "";
        text2 = "";
        operacao = ' ';
        contSoma = 0;
        contSubt = 0;
        contMult = 0;
        contDivi = 0;
        contPonto = 0;
        num1 = 0;
        num2 = 0; 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonDividir;
    private javax.swing.JButton jButtonIgualdade;
    private javax.swing.JButton jButtonMultiplicar;
    private javax.swing.JButton jButtonPonto;
    private javax.swing.JButton jButtonSomar;
    private javax.swing.JButton jButtonSubtrair;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
