package avaliacao11.view;

import avaliacao11.model.dao.ItensPedidosDao;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class CadastroItensPedidos extends javax.swing.JFrame {
    private ItensPedidosDao itePedDao;
    private ResultSet rs;
    private int count = 0;
    /**
     * Creates new form CadastroItensPedidos
     */
    public CadastroItensPedidos() {
        initComponents();
        limparCampos();
        setCamposTexto(false,false, false, false, false, false, false, false, false, false, false);
        tabelaItensPedidos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelPesquisaId = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButtonRetrocederRegistro = new javax.swing.JButton();
        jLabelProduto = new javax.swing.JLabel();
        jLabelInserirNovoRegistro = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jButtonAvancarRegistro = new javax.swing.JButton();
        jLabelCodigoProduto = new javax.swing.JLabel();
        jLabelPedido = new javax.swing.JLabel();
        jButtonIncluir = new javax.swing.JButton();
        jTextFieldCodigoProduto = new javax.swing.JTextField();
        jButtonAlterar = new javax.swing.JButton();
        jTextFieldDataPedido = new javax.swing.JTextField();
        jLabelCodigoPedido = new javax.swing.JLabel();
        jButtonExcluir = new javax.swing.JButton();
        jTextFieldCodigoPedido = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonFimRegistros = new javax.swing.JButton();
        jLabelDataPedido = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jLabelMovimentacaoRegistros = new javax.swing.JLabel();
        jButtonLocalizar = new javax.swing.JButton();
        jLabelRelacaoProdutoPedido = new javax.swing.JLabel();
        jButtonInicioRegistros = new javax.swing.JButton();
        jButtonTelaInicial = new javax.swing.JButton();
        jLabelValorTotal = new javax.swing.JLabel();
        jTextFieldValorTotal = new javax.swing.JTextField();
        jLabelDataCadastro = new javax.swing.JLabel();
        jTextFieldDataCadastro = new javax.swing.JTextField();
        jTextFieldQuantidadeAtual = new javax.swing.JTextField();
        jTextFieldQuantidadeInicial = new javax.swing.JTextField();
        jLabelDescricao = new javax.swing.JLabel();
        jTextFieldDescricao = new javax.swing.JTextField();
        jLabelPreco = new javax.swing.JLabel();
        jTextFieldPreco = new javax.swing.JTextField();
        jLabelUnidade = new javax.swing.JLabel();
        jTextFieldUnidade = new javax.swing.JTextField();
        jLabelQuantidadeAtual = new javax.swing.JLabel();
        jLabelQuantidadeInicial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro Produto - Pedido");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jLabelPesquisaId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPesquisaId.setText("ID do registro:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Localizar registro");

        jButtonRetrocederRegistro.setText("<");
        jButtonRetrocederRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetrocederRegistroActionPerformed(evt);
            }
        });

        jLabelProduto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelProduto.setText("Produto:");

        jLabelInserirNovoRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelInserirNovoRegistro.setText("Inserir novo registro");

        jTextFieldId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonAvancarRegistro.setText(">");
        jButtonAvancarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvancarRegistroActionPerformed(evt);
            }
        });

        jLabelCodigoProduto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCodigoProduto.setText("Código do produto:");

        jLabelPedido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPedido.setText("Pedido:");

        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jTextFieldCodigoProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setToolTipText("");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jTextFieldDataPedido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelCodigoPedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCodigoPedido.setText("Código do pedido:");
        jLabelCodigoPedido.setToolTipText("");

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTextFieldCodigoPedido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonFimRegistros.setText(">>");
        jButtonFimRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFimRegistrosActionPerformed(evt);
            }
        });

        jLabelDataPedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDataPedido.setText("Data do pedido:");
        jLabelDataPedido.setToolTipText("");

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jLabelMovimentacaoRegistros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMovimentacaoRegistros.setText("Movimentação de Registros: ");

        jButtonLocalizar.setText("Localizar");
        jButtonLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizarActionPerformed(evt);
            }
        });

        jLabelRelacaoProdutoPedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelRelacaoProdutoPedido.setText("Relação Produto - Pedido");

        jButtonInicioRegistros.setText("<<");
        jButtonInicioRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioRegistrosActionPerformed(evt);
            }
        });

        jButtonTelaInicial.setText("Tela Inicial");
        jButtonTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTelaInicialActionPerformed(evt);
            }
        });

        jLabelValorTotal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelValorTotal.setText("Valor total:");

        jTextFieldValorTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelDataCadastro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDataCadastro.setText("Data de cadastro:");

        jTextFieldDataCadastro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextFieldDataCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataCadastroActionPerformed(evt);
            }
        });

        jTextFieldQuantidadeAtual.setToolTipText("");
        jTextFieldQuantidadeAtual.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldQuantidadeInicial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelDescricao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDescricao.setText("Descrição:");

        jTextFieldDescricao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPreco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPreco.setText("Preço:");

        jTextFieldPreco.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelUnidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUnidade.setText("Unidade:");

        jTextFieldUnidade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelQuantidadeAtual.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelQuantidadeAtual.setText("Quantidade atual:");

        jLabelQuantidadeInicial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelQuantidadeInicial.setText("Quantidade inicial:");
        jLabelQuantidadeInicial.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelRelacaoProdutoPedido)
                .addGap(425, 425, 425))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jButtonNovo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLocalizar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonIncluir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(88, 88, 88)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldUnidade, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                            .addComponent(jTextFieldPreco)
                                            .addComponent(jTextFieldDescricao)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelProduto)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelPreco)
                                            .addComponent(jLabelDescricao)
                                            .addComponent(jLabelUnidade))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDataCadastro)
                                    .addComponent(jLabelQuantidadeAtual)
                                    .addComponent(jLabelQuantidadeInicial))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldQuantidadeInicial)
                                    .addComponent(jTextFieldDataCadastro)
                                    .addComponent(jTextFieldQuantidadeAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(jLabelInserirNovoRegistro)
                                        .addGap(256, 256, 256)
                                        .addComponent(jLabel11))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelPedido)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabelDataPedido)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButtonTelaInicial)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelCodigoPedido)
                                                .addComponent(jLabelCodigoProduto)
                                                .addComponent(jLabelValorTotal))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addComponent(jTextFieldCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(41, 41, 41)
                                                            .addComponent(jLabelPesquisaId))
                                                        .addComponent(jTextFieldCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(18, 18, 18)
                                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(0, 18, Short.MAX_VALUE)))))
                .addGap(149, 149, 149))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabelMovimentacaoRegistros)
                .addGap(18, 18, 18)
                .addComponent(jButtonInicioRegistros)
                .addGap(18, 18, 18)
                .addComponent(jButtonRetrocederRegistro)
                .addGap(18, 18, 18)
                .addComponent(jButtonAvancarRegistro)
                .addGap(18, 18, 18)
                .addComponent(jButtonFimRegistros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButtonTelaInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabelInserirNovoRegistro))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodigoProduto)
                    .addComponent(jLabelPesquisaId)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodigoPedido))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValorTotal))
                .addGap(42, 42, 42)
                .addComponent(jLabelRelacaoProdutoPedido)
                .addGap(11, 11, 11)
                .addComponent(jLabelProduto)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDescricao)
                    .addComponent(jLabelQuantidadeInicial)
                    .addComponent(jTextFieldQuantidadeInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPreco)
                    .addComponent(jLabelDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUnidade)
                    .addComponent(jLabelQuantidadeAtual)
                    .addComponent(jTextFieldQuantidadeAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jLabelPedido)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataPedido)
                    .addComponent(jTextFieldDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonLocalizar)
                    .addComponent(jButtonIncluir)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSair))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInicioRegistros)
                    .addComponent(jButtonRetrocederRegistro)
                    .addComponent(jButtonAvancarRegistro)
                    .addComponent(jButtonFimRegistros)
                    .addComponent(jLabelMovimentacaoRegistros))
                .addGap(32, 32, 32))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        //setCamposTexto(true, true, true, false, false, false, false, false, false, false, false);
        
        itePedDao.itensped.setCodItensPed(Integer.parseInt(jTextFieldId.getText()));
        itePedDao.itensped.setCodProd(Integer.parseInt(jTextFieldCodigoProduto.getText()));
        itePedDao.itensped.setCodPed(Integer.parseInt(jTextFieldCodigoPedido.getText()));
        itePedDao.itensped.setQtde(Float.parseFloat(jTextFieldValorTotal.getText()));
        
        JOptionPane.showMessageDialog(null, itePedDao.atualizar(ItensPedidosDao.ALTERACAO));
        limparCampos();
        tabelaItensPedidos();
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizarActionPerformed
        if (count == 0) {
            jTextFieldId.setEditable(true);
            jTextFieldId.requestFocus();
            count ++;
        }
        atualizarCampos();
    }//GEN-LAST:event_jButtonLocalizarActionPerformed

    private void jButtonInicioRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioRegistrosActionPerformed
        try {
            rs.first();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroItensPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        carregaDados();
    }//GEN-LAST:event_jButtonInicioRegistrosActionPerformed

    private void jTextFieldDataCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataCadastroActionPerformed

    private void jButtonTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTelaInicialActionPerformed
        setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_jButtonTelaInicialActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        limparCampos();
        setCamposTexto(true, true, true, false, false, false, false, false, false, false, false);
        setBotoes(false, false, true, false, false, true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        try {
            itePedDao = new ItensPedidosDao();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(CadastroItensPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (jTextFieldCodigoProduto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O código do produto não pode ser nulo!");
            jTextFieldCodigoProduto.requestFocus();
        }
        if (jTextFieldCodigoPedido.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O código do pedido não pode ser nulo!");
            jTextFieldCodigoPedido.requestFocus();
        }
        if (jTextFieldValorTotal.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O valor total não pode ser nulo!");
            jTextFieldValorTotal.requestFocus();
        }
        
        itePedDao.itensped.setCodProd(Integer.parseInt(jTextFieldCodigoProduto.getText()));
        itePedDao.itensped.setCodPed(Integer.parseInt(jTextFieldCodigoPedido.getText()));
        itePedDao.itensped.setQtde(Float.parseFloat(jTextFieldValorTotal.getText()));
        
        JOptionPane.showMessageDialog(null, itePedDao.atualizar(ItensPedidosDao.INCLUSAO));
        limparCampos();
        tabelaItensPedidos();
        
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        itePedDao.itensped.setCodItensPed(Integer.parseInt(jTextFieldId.getText()));
        itePedDao.localizar();
        
        int confirmacao = JOptionPane.showConfirmDialog(null, itePedDao.itensped.getCodItensPed(), "Apagar o registro?", JOptionPane.YES_OPTION);
        if (confirmacao == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, itePedDao.atualizar(ItensPedidosDao.EXCLUSAO));
            limparCampos();
            tabelaItensPedidos();
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        setCamposTexto(true, true, true, false, false, false, false, false, false, false, false);
        limparCampos();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonRetrocederRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetrocederRegistroActionPerformed
        try {
            rs.previous();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroItensPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        carregaDados();
    }//GEN-LAST:event_jButtonRetrocederRegistroActionPerformed

    private void jButtonAvancarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvancarRegistroActionPerformed
        try {
            rs.next();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroItensPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        carregaDados();
    }//GEN-LAST:event_jButtonAvancarRegistroActionPerformed

    private void jButtonFimRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFimRegistrosActionPerformed
        try {
            rs.last();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroItensPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        carregaDados();
    }//GEN-LAST:event_jButtonFimRegistrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroItensPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroItensPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroItensPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroItensPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroItensPedidos().setVisible(true);
            }
        });
    }
    
    
    public void setCamposTexto(boolean codigoProduto, boolean codigoPedido, boolean valorTotal, boolean id, boolean descricao, boolean preco, boolean unidade, boolean qtdeInicial, boolean dataCad, boolean qtdeAtual, boolean dataPed) {
        jTextFieldCodigoProduto.setEditable(codigoProduto);
        jTextFieldCodigoPedido.setEditable(codigoPedido);
        jTextFieldValorTotal.setEditable(valorTotal);
        jTextFieldId.setEditable(id);
        jTextFieldDescricao.setEditable(descricao);
        jTextFieldPreco.setEditable(preco);
        jTextFieldUnidade.setEditable(unidade);
        jTextFieldQuantidadeInicial.setEditable(qtdeInicial);
        jTextFieldDataCadastro.setEditable(dataCad );
        jTextFieldQuantidadeAtual.setEditable(qtdeAtual);
        jTextFieldDataPedido.setEditable(dataPed);
    }
    
    public void setBotoes (boolean buttonNovo, boolean buttonLocalizar, boolean buttonIncluir, boolean buttonAlterar, boolean buttonExcluir, boolean buttonCancelar) {
        jButtonNovo.setEnabled(buttonNovo);
        jButtonLocalizar.setEnabled(buttonLocalizar);
        jButtonIncluir.setEnabled(buttonIncluir);
        jButtonAlterar.setEnabled(buttonAlterar);
        jButtonExcluir.setEnabled(buttonExcluir);
        jButtonCancelar.setEnabled(buttonCancelar);
    }
    
    public void limparCampos() {
        jTextFieldCodigoProduto.setText("");
        jTextFieldCodigoPedido.setText("");
        jTextFieldValorTotal.setText("");
        jTextFieldId.setText("");
        jTextFieldDescricao.setText("");
        jTextFieldPreco.setText("");
        jTextFieldUnidade.setText("");
        jTextFieldQuantidadeInicial.setText("");
        jTextFieldDataCadastro.setText("");
        jTextFieldQuantidadeAtual.setText("");
        jTextFieldDataPedido.setText("");
        jTextFieldCodigoProduto.requestFocus();
        count = 0;
        setBotoes(true, true, false, false, false, true);
    }
    
    public void tabelaItensPedidos() {
        try {
            itePedDao = new ItensPedidosDao();
            String sql = """
                        select * from itensped 
                        inner join produtos on produtos.codProd = itensped.Produtos_codProd 
                        inner join pedidos on pedidos.codPed = itensped.Pedidos_codPed 
                         """;
            PreparedStatement stmt = itePedDao.c.prepareStatement(sql);
            rs = stmt.executeQuery();
        } catch (SQLException | ClassNotFoundException error) {
            JOptionPane.showMessageDialog(null, "Problemas na conexão!\n" + error.toString());
        }
    }
    
    public void atualizarCampos() {
        itePedDao.itensped.setCodItensPed(Integer.parseInt(jTextFieldId.getText()));
        if (itePedDao.localizar()) {
            // Itens - Pedidos
            jTextFieldId.setText(Integer.toString(itePedDao.itensped.getCodItensPed()));
            jTextFieldCodigoProduto.setText(Integer.toString(itePedDao.itensped.getCodProd()));
            jTextFieldCodigoPedido.setText(Integer.toString(itePedDao.itensped.getCodPed()));
            jTextFieldValorTotal.setText(Float.toString(itePedDao.itensped.getQtde()));
            // Produto
            jTextFieldDescricao.setText(itePedDao.produto.getDescricao());
            jTextFieldPreco.setText(Float.toString(itePedDao.produto.getPreco()));
            jTextFieldUnidade.setText(itePedDao.produto.getUnidade());
            jTextFieldQuantidadeInicial.setText(Float.toString(itePedDao.produto.getQtdeInicial()));
            jTextFieldDataCadastro.setText(converterData(itePedDao.produto.getDataCad().toString()));
            jTextFieldQuantidadeAtual.setText(Float.toString(itePedDao.produto.getQtdeAtual()));
            // Pedido
            jTextFieldDataPedido.setText(converterData(itePedDao.pedido.getData().toString()));
            setCamposTexto(true,true, true, false, false, false, false, false, false, false, false);
            setBotoes(true,true,false,true,true,true);
        } else {
            JOptionPane.showMessageDialog(null , "Registro não encontrado!", "Falha na localização", JOptionPane.WARNING_MESSAGE);
            limparCampos();
        }
    }
    
    public String converterData (String data) {
        // 2023-06-13
        String ano = data.substring(0, 4); // 2023
        String mes = data.substring(5, 7); // 06
        String dia = data.substring(8, 10); // 13
        String r = dia + "/" + mes + "/" + ano; // 13/06/2023
        return r;
    }
    
    public void carregaDados() {
        try {
            if (rs.isAfterLast()) {
                rs.last();
            } else if (rs.isBeforeFirst()) {
                rs.first();
            } 
            jTextFieldId.setText(Integer.toString(rs.getInt("codItensPed")));
            jTextFieldCodigoProduto.setText(Integer.toString(rs.getInt("Produtos_codProd")));
            jTextFieldCodigoPedido.setText(Integer.toString(rs.getInt("Pedidos_codPed")));
            jTextFieldValorTotal.setText(Float.toString(rs.getFloat("qtde")));
            // Produto
            jTextFieldDescricao.setText(rs.getString("descricao"));
            jTextFieldPreco.setText(Float.toString(rs.getFloat("preco")));
            jTextFieldUnidade.setText(rs.getString("unidade"));
            jTextFieldQuantidadeInicial.setText(Float.toString(rs.getFloat("qtdeInicial")));
            jTextFieldDataCadastro.setText(converterData(rs.getDate("dataCad").toString()));
            jTextFieldQuantidadeAtual.setText(Float.toString(rs.getFloat("qtdeAtual")));
            // Pedido
            jTextFieldDataPedido.setText(converterData(rs.getDate("data").toString()));
            setBotoes(true,true,false,true,true,true);
            setCamposTexto(true,true, true, false, false, false, false, false, false, false, false);
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "Erro na conexão!\n" + error.toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonAvancarRegistro;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFimRegistros;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonInicioRegistros;
    private javax.swing.JButton jButtonLocalizar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonRetrocederRegistro;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonTelaInicial;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabelCodigoPedido;
    private javax.swing.JLabel jLabelCodigoProduto;
    private javax.swing.JLabel jLabelDataCadastro;
    private javax.swing.JLabel jLabelDataPedido;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelInserirNovoRegistro;
    private javax.swing.JLabel jLabelMovimentacaoRegistros;
    private javax.swing.JLabel jLabelPedido;
    private javax.swing.JLabel jLabelPesquisaId;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JLabel jLabelProduto;
    private javax.swing.JLabel jLabelQuantidadeAtual;
    private javax.swing.JLabel jLabelQuantidadeInicial;
    private javax.swing.JLabel jLabelRelacaoProdutoPedido;
    private javax.swing.JLabel jLabelUnidade;
    private javax.swing.JLabel jLabelValorTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCodigoPedido;
    private javax.swing.JTextField jTextFieldCodigoProduto;
    private javax.swing.JTextField jTextFieldDataCadastro;
    private javax.swing.JTextField jTextFieldDataPedido;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JTextField jTextFieldQuantidadeAtual;
    private javax.swing.JTextField jTextFieldQuantidadeInicial;
    private javax.swing.JTextField jTextFieldUnidade;
    private javax.swing.JTextField jTextFieldValorTotal;
    // End of variables declaration//GEN-END:variables
}
