package avaliacao11.view;

import java.sql.*;
import javax.swing.JOptionPane;
import avaliacao11.model.dao.ClientesDao;
import java.util.logging.Level;
import java.util.logging.Logger;


public final class CadastroClientes extends javax.swing.JFrame {
    private ClientesDao clienDao;
    private ResultSet rs;
    int count = 0;
    /**
     * Creates new form CadastroClientes
     */
    public CadastroClientes() {
        initComponents();
        setBotoes(true,true,false,false,false,false);
        jTextFieldId.setEditable(false);
        jTextFieldNome.requestFocus();
        tabelaClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCep = new javax.swing.JTextField();
        jButtonFimRegistros = new javax.swing.JButton();
        jLabelUf = new javax.swing.JLabel();
        jTextFieldFone = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelFone = new javax.swing.JLabel();
        jTextFieldCelular = new javax.swing.JTextField();
        jLabelCelular = new javax.swing.JLabel();
        jTextFieldUf = new javax.swing.JTextField();
        jLabelCep = new javax.swing.JLabel();
        jButtonNovo = new javax.swing.JButton();
        jButtonLocalizar = new javax.swing.JButton();
        jButtonIncluir = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jButtonExcluir = new javax.swing.JButton();
        jTextFieldNome = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jLabelEndereco = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jButtonSair = new javax.swing.JButton();
        jLabelBairro = new javax.swing.JLabel();
        jLabelMovimentacaoRegistros = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jButtonInicioRegistros = new javax.swing.JButton();
        jLabelCidade = new javax.swing.JLabel();
        jButtonRetrocederRegistro = new javax.swing.JButton();
        jTextFieldCidade = new javax.swing.JTextField();
        jButtonAvançarRegistro = new javax.swing.JButton();
        jLabelPesquisaId = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jButtonTelaInicial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Clientes");
        setResizable(false);

        jButtonFimRegistros.setText(">>");
        jButtonFimRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFimRegistrosActionPerformed(evt);
            }
        });

        jLabelUf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUf.setText("UF:");

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEmail.setText("E-mail:");

        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jLabelFone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelFone.setText("Fone:");

        jLabelCelular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCelular.setText("Celular:");

        jLabelCep.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCep.setText("CEP:");

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonLocalizar.setText("Localizar");
        jButtonLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizarActionPerformed(evt);
            }
        });

        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setToolTipText("");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNome.setText("Nome:");

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelEndereco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEndereco.setText("Endereço:");

        jTextFieldEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabelBairro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelBairro.setText("Bairro:");
        jLabelBairro.setToolTipText("");

        jLabelMovimentacaoRegistros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMovimentacaoRegistros.setText("Movimentação de Registros");

        jButtonInicioRegistros.setText("<<");
        jButtonInicioRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioRegistrosActionPerformed(evt);
            }
        });

        jLabelCidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCidade.setText("Cidade:");

        jButtonRetrocederRegistro.setText("<");
        jButtonRetrocederRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetrocederRegistroActionPerformed(evt);
            }
        });

        jButtonAvançarRegistro.setText(">");
        jButtonAvançarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvançarRegistroActionPerformed(evt);
            }
        });

        jLabelPesquisaId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPesquisaId.setText("ID do cliente: ");

        jTextFieldId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonTelaInicial.setText("Tela Inicial");
        jButtonTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTelaInicialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabelMovimentacaoRegistros)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonInicioRegistros)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonRetrocederRegistro)
                                .addGap(33, 33, 33)
                                .addComponent(jButtonAvançarRegistro)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonFimRegistros)
                                .addGap(184, 184, 184))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonNovo)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonLocalizar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonIncluir)
                                .addGap(32, 32, 32)
                                .addComponent(jButtonAlterar)
                                .addGap(37, 37, 37)
                                .addComponent(jButtonExcluir)
                                .addGap(30, 30, 30)
                                .addComponent(jButtonCancelar)
                                .addGap(31, 31, 31)
                                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelEmail)
                                            .addComponent(jLabelFone)
                                            .addComponent(jLabelUf)))
                                    .addComponent(jLabelCelular))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldCelular)
                                    .addComponent(jTextFieldFone)
                                    .addComponent(jTextFieldUf)
                                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonTelaInicial, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome)
                            .addComponent(jLabelEndereco)
                            .addComponent(jLabelBairro)
                            .addComponent(jLabelCidade)
                            .addComponent(jLabelCep))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jLabelPesquisaId)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButtonTelaInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPesquisaId))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNome)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEndereco)
                            .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBairro))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCidade)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUf)
                            .addComponent(jTextFieldUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEmail))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFone))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCelular))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCep))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonLocalizar)
                    .addComponent(jButtonIncluir)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSair))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInicioRegistros)
                    .addComponent(jButtonRetrocederRegistro)
                    .addComponent(jButtonAvançarRegistro)
                    .addComponent(jButtonFimRegistros)
                    .addComponent(jLabelMovimentacaoRegistros))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        try {
            clienDao = new ClientesDao() ;
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(CadastroClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        clienDao.cliente.setCodCliente(Integer.parseInt(jTextFieldId.getText()));
        
        clienDao.cliente.setNome(jTextFieldNome.getText());
        clienDao.cliente.setEndereco(jTextFieldEndereco.getText());
        clienDao.cliente.setBairro(jTextFieldBairro.getText());
        clienDao.cliente.setCidade(jTextFieldCidade.getText());
        clienDao.cliente.setCep(jTextFieldCep.getText());
        clienDao.cliente.setUf(jTextFieldUf.getText());
        clienDao.cliente.setEmail(jTextFieldEmail.getText());
        clienDao.cliente.setFone(jTextFieldFone.getText());
        clienDao.cliente.setCelular(jTextFieldCelular.getText());
        
        JOptionPane.showMessageDialog(null, clienDao.atualizar(ClientesDao.ALTERACAO));
        limparCampos();
        tabelaClientes();
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonInicioRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioRegistrosActionPerformed
        try {
            rs.first();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        carregaDados();
    }//GEN-LAST:event_jButtonInicioRegistrosActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        limparCampos();
        setBotoes(false,false,true,false,false,true);
        jTextFieldNome.requestFocus();
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizarActionPerformed
        try {
            clienDao = new ClientesDao() ;
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(CadastroClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (count == 0) {
            jTextFieldId.setEditable(true);
            jTextFieldId.requestFocus();
            count++;
        } else {
            atualizarCampos();
        }
    }//GEN-LAST:event_jButtonLocalizarActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        try {
            clienDao = new ClientesDao() ;
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(CadastroClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (jTextFieldNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O nome não pode ser vazio!");
            jTextFieldNome.requestFocus();
        }
        if (jTextFieldEndereco.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O endereço não pode ser vazio");
            jTextFieldEndereco.requestFocus();
        }
        if (jTextFieldBairro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O bairro não pode ser vazio!");
            jTextFieldBairro.requestFocus();
        }
        if (jTextFieldCidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "A cidade não pode ser vazia!");
            jTextFieldCidade.requestFocus();
        }
        if (jTextFieldCep.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O cep não pode ser vazio");
            jTextFieldCep.requestFocus();
        }
        if (jTextFieldUf.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "A UF não pode ser vazia!");
            jTextFieldUf.requestFocus();
        }
        if (jTextFieldEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O email não pode ser vazio!");
            jTextFieldEmail.requestFocus();
        }
        if (jTextFieldCelular.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O número de celular não pode ser vazio!");
            jTextFieldCelular.requestFocus();
        }
        
        clienDao.cliente.setNome(jTextFieldNome.getText());
        clienDao.cliente.setEndereco(jTextFieldEndereco.getText());
        clienDao.cliente.setBairro(jTextFieldBairro.getText());
        clienDao.cliente.setCidade(jTextFieldCidade.getText());
        clienDao.cliente.setCep(jTextFieldCep.getText());
        clienDao.cliente.setUf(jTextFieldUf.getText());
        clienDao.cliente.setEmail(jTextFieldEmail.getText());
        clienDao.cliente.setFone(jTextFieldFone.getText());
        clienDao.cliente.setCelular(jTextFieldCelular.getText());
                
        JOptionPane.showMessageDialog(null, clienDao.atualizar(ClientesDao.INCLUSAO));
        limparCampos();
        tabelaClientes();
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        try {
            clienDao = new ClientesDao() ;
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(CadastroClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        clienDao.cliente.setCodCliente(Integer.parseInt(jTextFieldId.getText()));
        clienDao.localizar();
        
        int confirmacao = JOptionPane.showConfirmDialog(null, clienDao.cliente.getNome(), "Excluir o cliente?", JOptionPane.YES_NO_OPTION);
        if (confirmacao == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, clienDao.atualizar(ClientesDao.EXCLUSAO)); 
        }
        limparCampos();
        tabelaClientes();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        limparCampos();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonFimRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFimRegistrosActionPerformed
        try {
            rs.last();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        carregaDados();
    }//GEN-LAST:event_jButtonFimRegistrosActionPerformed

    private void jButtonRetrocederRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetrocederRegistroActionPerformed
        try {
            rs.previous();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        carregaDados();
    }//GEN-LAST:event_jButtonRetrocederRegistroActionPerformed

    private void jButtonAvançarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvançarRegistroActionPerformed
        try {
            rs.next();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        carregaDados();
    }//GEN-LAST:event_jButtonAvançarRegistroActionPerformed

    private void jButtonTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTelaInicialActionPerformed
        setVisible(false);
        Menu menu = new Menu ();
        menu.setVisible(true);
    }//GEN-LAST:event_jButtonTelaInicialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CadastroClientes().setVisible(true);
        });
    }
    
    public void limparCampos() {
        jTextFieldId.setEditable(false);
        count = 0;
        jTextFieldNome.requestFocus();
        jTextFieldId.setText("");
        jTextFieldNome.setText("");
        jTextFieldEndereco.setText("");
        jTextFieldBairro.setText("");
        jTextFieldCidade.setText("");
        jTextFieldCep.setText("");
        jTextFieldUf.setText("");
        jTextFieldEmail.setText("");
        jTextFieldFone.setText("");
        jTextFieldCelular.setText("");
        setBotoes(true,true,false,false,false,true);
    }
    
    public void atualizarCampos() {
        clienDao.cliente.setCodCliente(Integer.parseInt(jTextFieldId.getText()));
        if (clienDao.localizar()) {
            jTextFieldId.setText(Integer.toString(clienDao.cliente.getCodCliente()));
            jTextFieldNome.setText(clienDao.cliente.getNome());
            jTextFieldEndereco.setText(clienDao.cliente.getEndereco());
            jTextFieldBairro.setText(clienDao.cliente.getBairro());
            jTextFieldCidade.setText(clienDao.cliente.getCidade());
            jTextFieldCep.setText(clienDao.cliente.getCep());
            jTextFieldUf.setText(clienDao.cliente.getUf());
            jTextFieldEmail.setText(clienDao.cliente.getEmail());
            jTextFieldFone.setText(clienDao.cliente.getFone());
            jTextFieldCelular.setText(clienDao.cliente.getCelular());
            setBotoes(false,true,false,true,true,true);
        } else {
            JOptionPane.showMessageDialog(null, "Cliente não encontrado!", "Falha na localização", JOptionPane.ERROR_MESSAGE);
            limparCampos();
        }
    }

    
    public void setBotoes(boolean buttonNovo, boolean buttonLocalizar, boolean buttonIncluir, boolean buttonAlterar, boolean buttonExcluir, boolean buttonCancelar) {
        jButtonNovo.setEnabled(buttonNovo);
        jButtonLocalizar.setEnabled(buttonLocalizar);
        jButtonIncluir.setEnabled(buttonIncluir);
        jButtonAlterar.setEnabled(buttonAlterar);
        jButtonExcluir.setEnabled(buttonExcluir);
        jButtonCancelar.setEnabled(buttonCancelar);
    }
    
    public void tabelaClientes () {
        try {
            clienDao = new ClientesDao();
            String sql = "select * from clientes";
            PreparedStatement stmt = clienDao.c.prepareStatement(sql);
            rs = stmt.executeQuery();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Problemas na conexão!\n" + ex.toString());
        }
    }
    
    public void carregaDados() {
        try {
            if (rs.isAfterLast()) {
                rs.last();
            }
            if (rs.isBeforeFirst()) {
                rs.first();
            }
            
            jTextFieldId.setText(Integer.toString(rs.getInt("codCliente")));
            jTextFieldNome.setText(rs.getString("nome"));
            jTextFieldEndereco.setText(rs.getString("ender"));
            jTextFieldBairro.setText(rs.getString("bairro"));
            jTextFieldCidade.setText(rs.getString("cidade"));
            jTextFieldCep.setText(rs.getString("cep"));
            jTextFieldUf.setText(rs.getString("uf"));
            jTextFieldEmail.setText(rs.getString("email"));
            jTextFieldFone.setText(rs.getString("fone"));
            jTextFieldCelular.setText(rs.getString("celular"));
            setBotoes(true,true,false,true,true,true);
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Problemas na conexão!\n" + erro.toString());
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonAvançarRegistro;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFimRegistros;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonInicioRegistros;
    private javax.swing.JButton jButtonLocalizar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonRetrocederRegistro;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonTelaInicial;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelFone;
    private javax.swing.JLabel jLabelMovimentacaoRegistros;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPesquisaId;
    private javax.swing.JLabel jLabelUf;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldCep;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldFone;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldUf;
    // End of variables declaration//GEN-END:variables
}
