package avaliacao11.view;

import java.sql.*;
import java.text.*;
import avaliacao11.model.dao.PedidosDao;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class CadastroPedidos extends javax.swing.JFrame {
    private PedidosDao pedDao;
    private ResultSet rs;
    private int count = 0;
    /**
     * Creates new form CadastroPedidos
     */
    public CadastroPedidos() {
        initComponents();
        limparCampos();
        setCamposTexto (false, false, false, false, false, false, false, false, false, false, false, false, false);
        tabelaPedidos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldEndereco = new javax.swing.JTextField();
        jLabelBairro = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabelCidade = new javax.swing.JLabel();
        jTextFieldCidade = new javax.swing.JTextField();
        jLabelCelular = new javax.swing.JLabel();
        jTextFieldUf = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldCep = new javax.swing.JTextField();
        jLabelUf = new javax.swing.JLabel();
        jTextFieldFone = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelFone = new javax.swing.JLabel();
        jTextFieldCelular = new javax.swing.JTextField();
        jLabelEndereco = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldId = new javax.swing.JTextField();
        jButtonAvancarRegistro = new javax.swing.JButton();
        jLabelPedido = new javax.swing.JLabel();
        jTextFieldUf1 = new javax.swing.JTextField();
        jTextFieldEndereco1 = new javax.swing.JTextField();
        jLabelCep = new javax.swing.JLabel();
        jTextFieldDataPedido1 = new javax.swing.JTextField();
        jLabelNome1 = new javax.swing.JLabel();
        jLabelBairro1 = new javax.swing.JLabel();
        jTextFieldNome1 = new javax.swing.JTextField();
        javax.swing.JLabel jLabelDataPedido1 = new javax.swing.JLabel();
        jTextFieldCep1 = new javax.swing.JTextField();
        jTextFieldBairro1 = new javax.swing.JTextField();
        jLabelUf1 = new javax.swing.JLabel();
        jLabelRelacaoClientePedido = new javax.swing.JLabel();
        jTextFieldFone1 = new javax.swing.JTextField();
        jLabelCidade1 = new javax.swing.JLabel();
        jLabelEmail1 = new javax.swing.JLabel();
        jLabelLocalizarPedido = new javax.swing.JLabel();
        jTextFieldCidade1 = new javax.swing.JTextField();
        jTextFieldEmail1 = new javax.swing.JTextField();
        jLabelFone1 = new javax.swing.JLabel();
        jLabelCelular1 = new javax.swing.JLabel();
        jLabelCodigoCliente = new javax.swing.JLabel();
        jButtonIncluir = new javax.swing.JButton();
        jTextFieldCodigoCliente = new javax.swing.JTextField();
        jButtonAlterar = new javax.swing.JButton();
        jLabelDataPedido = new javax.swing.JLabel();
        jButtonExcluir = new javax.swing.JButton();
        jTextFieldDataPedido = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonFimRegistros = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jLabelMovimentacaoRegistros = new javax.swing.JLabel();
        jButtonLocalizar = new javax.swing.JButton();
        jButtonInicioRegistros = new javax.swing.JButton();
        jTextFieldCelular1 = new javax.swing.JTextField();
        jLabelPesquisaId = new javax.swing.JLabel();
        jLabelEndereco1 = new javax.swing.JLabel();
        jButtonRetrocederRegistro = new javax.swing.JButton();
        jLabelCliente = new javax.swing.JLabel();
        jLabelInserirNovoRegistro = new javax.swing.JLabel();
        jButtonTelaInicial = new javax.swing.JButton();

        jLabelBairro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelBairro.setText("Bairro:");
        jLabelBairro.setToolTipText("");

        jLabelCidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCidade.setText("Cidade:");

        jLabelCelular.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCelular.setText("Celular:");

        jLabelNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNome.setText("Nome:");

        jLabelUf.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUf.setText("UF:");

        jLabelEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEmail.setText("E-mail:");

        jLabelFone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelFone.setText("Fone:");

        jLabelEndereco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEndereco.setText("Endereço:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Pedidos");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTextFieldId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonAvancarRegistro.setText(">");
        jButtonAvancarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvancarRegistroActionPerformed(evt);
            }
        });

        jLabelPedido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPedido.setText("Pedido:");

        jTextFieldUf1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldEndereco1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextFieldEndereco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEndereco1ActionPerformed(evt);
            }
        });

        jLabelCep.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCep.setText("CEP:");

        jTextFieldDataPedido1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelNome1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNome1.setText("Nome:");

        jLabelBairro1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelBairro1.setText("Bairro:");
        jLabelBairro1.setToolTipText("");

        jTextFieldNome1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextFieldNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNome1ActionPerformed(evt);
            }
        });

        jLabelDataPedido1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDataPedido1.setText("Data do pedido:");
        jLabelDataPedido1.setToolTipText("");

        jTextFieldCep1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldBairro1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelUf1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUf1.setText("UF:");

        jLabelRelacaoClientePedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelRelacaoClientePedido.setText("Relação Cliente - Pedido");

        jTextFieldFone1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelCidade1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCidade1.setText("Cidade:");

        jLabelEmail1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEmail1.setText("E-mail:");

        jLabelLocalizarPedido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelLocalizarPedido.setText("Localizar pedido");

        jTextFieldCidade1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldEmail1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextFieldEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmail1ActionPerformed(evt);
            }
        });

        jLabelFone1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelFone1.setText("Fone:");

        jLabelCelular1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCelular1.setText("Celular:");

        jLabelCodigoCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelCodigoCliente.setText("Código do cliente:");

        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jTextFieldCodigoCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setToolTipText("");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jLabelDataPedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDataPedido.setText("Data do pedido:");
        jLabelDataPedido.setToolTipText("");

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jTextFieldDataPedido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonFimRegistros.setText(">>");
        jButtonFimRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFimRegistrosActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jLabelMovimentacaoRegistros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMovimentacaoRegistros.setText("Movimentação de Registros: ");

        jButtonLocalizar.setText("Localizar");
        jButtonLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizarActionPerformed(evt);
            }
        });

        jButtonInicioRegistros.setText("<<");
        jButtonInicioRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioRegistrosActionPerformed(evt);
            }
        });

        jTextFieldCelular1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelPesquisaId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPesquisaId.setText("ID do pedido:");

        jLabelEndereco1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelEndereco1.setText("Endereço:");

        jButtonRetrocederRegistro.setText("<");
        jButtonRetrocederRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetrocederRegistroActionPerformed(evt);
            }
        });

        jLabelCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelCliente.setText("Cliente:");

        jLabelInserirNovoRegistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelInserirNovoRegistro.setText("Inserir novo registro");

        jButtonTelaInicial.setText("Tela Inicial");
        jButtonTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTelaInicialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jButtonNovo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLocalizar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonIncluir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAlterar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabelMovimentacaoRegistros)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInicioRegistros)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRetrocederRegistro)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonAvancarRegistro)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFimRegistros)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(477, 477, 477)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldUf1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldFone1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCelular1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelNome1)
                                            .addComponent(jLabelEndereco1)
                                            .addComponent(jLabelBairro1)
                                            .addComponent(jLabelCidade1))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextFieldEndereco1)
                                                .addComponent(jTextFieldBairro1, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTextFieldCidade1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelCep)
                                        .addGap(50, 50, 50)
                                        .addComponent(jTextFieldCep1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabelPedido)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabelDataPedido1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldDataPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabelCliente)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabelInserirNovoRegistro)
                        .addGap(256, 256, 256)
                        .addComponent(jLabelLocalizarPedido))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(jLabelRelacaoClientePedido))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUf1)
                            .addComponent(jLabelEmail1)
                            .addComponent(jLabelFone1)
                            .addComponent(jLabelCelular1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonTelaInicial)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabelDataPedido)
                                .addComponent(jLabelCodigoCliente))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jTextFieldCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(jLabelPesquisaId)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(162, 162, 162))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButtonTelaInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLocalizarPedido)
                    .addComponent(jLabelInserirNovoRegistro))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodigoCliente)
                    .addComponent(jLabelPesquisaId)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDataPedido))
                .addGap(40, 40, 40)
                .addComponent(jLabelRelacaoClientePedido)
                .addGap(16, 16, 16)
                .addComponent(jLabelCliente)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNome1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelUf1)
                        .addComponent(jTextFieldUf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEndereco1)
                            .addComponent(jTextFieldEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEmail1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBairro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelBairro1))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCidade1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCep1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCep)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldFone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFone1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCelular1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCelular1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabelPedido)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataPedido1)
                    .addComponent(jTextFieldDataPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonLocalizar)
                    .addComponent(jButtonIncluir)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSair))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInicioRegistros)
                    .addComponent(jButtonRetrocederRegistro)
                    .addComponent(jButtonAvancarRegistro)
                    .addComponent(jButtonFimRegistros)
                    .addComponent(jLabelMovimentacaoRegistros))
                .addGap(72, 72, 72))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(404, 404, 404))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEndereco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEndereco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEndereco1ActionPerformed

    private void jTextFieldNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNome1ActionPerformed

    private void jTextFieldEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmail1ActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        pedDao.pedido.setCodPed(Integer.parseInt(jTextFieldId.getText()));
        pedDao.pedido.setCodCliente(Integer.parseInt(jTextFieldCodigoCliente.getText()));
        
        Date data = new Date();
        String dataString = jTextFieldDataPedido.getText();
        SimpleDateFormat format = new SimpleDateFormat ("dd/MM/yyyy");
        
        try {
            data = format.parse(dataString);
            java.sql.Date dataSql = new java.sql.Date (data.getTime()); // A passagem do valor de timestamp obtido por getTime() ao construtor de java.sql.Date permite criar um objeto java.sql.Date com a mesma data e hora de um objeto do tipo Date 
            pedDao.pedido.setData(dataSql);
        } catch (ParseException error) {
           Logger.getLogger(CadastroPedidos.class.getName()).log(Level.SEVERE, null, error);

        }
        
        JOptionPane.showMessageDialog(null, pedDao.atualizar(PedidosDao.ALTERACAO));
        limparCampos();
        tabelaPedidos();
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizarActionPerformed
        if (count == 0) {
            setCamposTexto(false, false, true, false, false, false, false, false, false, false, false, false, false);
            jTextFieldId.requestFocus();
            count ++;
        } else {
            atualizarCampos();
        }
    }//GEN-LAST:event_jButtonLocalizarActionPerformed

    private void jButtonInicioRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioRegistrosActionPerformed
        try {
            rs.first();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        carregaDados();
    }//GEN-LAST:event_jButtonInicioRegistrosActionPerformed

    private void jButtonTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTelaInicialActionPerformed
        setVisible(false);
        Menu menu = new Menu ();
        menu.setVisible(true);
    }//GEN-LAST:event_jButtonTelaInicialActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        limparCampos();
        setCamposTexto (true, true, false, false, false, false, false, false, false, false, false, false, false);
        setBotoes(false, false, true, false, false, true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        pedDao.pedido.setCodPed(Integer.parseInt(jTextFieldId.getText()));
        pedDao.localizar();
        
        int confirmacao = JOptionPane.showConfirmDialog(null, pedDao.pedido.getCodPed(), "Excluir o pedido?", JOptionPane.YES_NO_OPTION);
        if (confirmacao == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, pedDao.atualizar(PedidosDao.EXCLUSAO));
        }
        limparCampos();
        tabelaPedidos();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        try {
            pedDao = new PedidosDao();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(CadastroPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (jTextFieldCodigoCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O código do cliente não pode ser nulo!");
            jTextFieldCodigoCliente.requestFocus();
        }
        if (jTextFieldDataPedido.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "A data do pedido não pode ser nula!");
            jTextFieldDataPedido.requestFocus();
        }
        
        pedDao.pedido.setCodCliente(Integer.parseInt(jTextFieldCodigoCliente.getText()));
        
        Date data = new Date();
        String dataString = jTextFieldDataPedido.getText();
        SimpleDateFormat format = new SimpleDateFormat ("dd/MM/yyyy");
        
        try {
            data = format.parse(dataString);
            java.sql.Date dataSql = new java.sql.Date (data.getTime()); // A passagem do valor de timestamp obtido por getTime() ao construtor de java.sql.Date permite criar um objeto java.sql.Date com a mesma data e hora de um objeto do tipo Date 
            pedDao.pedido.setData(dataSql);
        } catch (ParseException error) {
           Logger.getLogger(CadastroPedidos.class.getName()).log(Level.SEVERE, null, error);

        }
        
        JOptionPane.showMessageDialog(null, pedDao.atualizar(PedidosDao.INCLUSAO));
        limparCampos();
        tabelaPedidos();
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        limparCampos();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonRetrocederRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetrocederRegistroActionPerformed
        try {
            rs.previous();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        carregaDados();
    }//GEN-LAST:event_jButtonRetrocederRegistroActionPerformed

    private void jButtonAvancarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvancarRegistroActionPerformed
        try {
            rs.next();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        carregaDados();
    }//GEN-LAST:event_jButtonAvancarRegistroActionPerformed

    private void jButtonFimRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFimRegistrosActionPerformed
        try {
            rs.last();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        carregaDados();
    }//GEN-LAST:event_jButtonFimRegistrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPedidos().setVisible(true);
            }
        });
    }
    
   public void setCamposTexto (boolean codigoCliente, boolean dataPedido, boolean id, boolean nome, 
           boolean endereco, boolean bairro, boolean cidade, boolean cep, boolean uf, boolean email, 
           boolean fone, boolean celular, boolean dataPed) {
       jTextFieldCodigoCliente.setEditable(codigoCliente);
       jTextFieldDataPedido.setEditable(dataPedido);
       jTextFieldId.setEditable(id);
       jTextFieldNome1.setEditable(nome);
       jTextFieldEndereco1.setEditable(endereco);
       jTextFieldBairro1.setEditable(bairro);
       jTextFieldCidade1.setEditable(cidade);
       jTextFieldCep1.setEditable(cep);
       jTextFieldUf1.setEditable(uf);
       jTextFieldEmail1.setEditable(email);
       jTextFieldFone1.setEditable(fone);
       jTextFieldCelular1.setEditable(celular);
       jTextFieldDataPedido1.setEditable(dataPed);
   }
    
   public void setBotoes (boolean buttonNovo, boolean buttonLocalizar, boolean buttonIncluir, boolean buttonAlterar, 
           boolean buttonExcluir, boolean buttonCancelar) {
        jButtonNovo.setEnabled(buttonNovo);
        jButtonLocalizar.setEnabled(buttonLocalizar);
        jButtonIncluir.setEnabled(buttonIncluir);
        jButtonAlterar.setEnabled(buttonAlterar);
        jButtonExcluir.setEnabled(buttonExcluir);
        jButtonCancelar.setEnabled(buttonCancelar);
    }
    
    public void limparCampos() {
        jTextFieldCodigoCliente.setText("");
        jTextFieldDataPedido.setText("");
        jTextFieldId.setText("");
        jTextFieldNome1.setText("");
        jTextFieldEndereco1.setText("");
        jTextFieldBairro1.setText("");
        jTextFieldCidade1.setText("");
        jTextFieldCep1.setText("");
        jTextFieldUf1.setText("");
        jTextFieldEmail1.setText("");
        jTextFieldFone1.setText("");
        jTextFieldCelular1.setText("");
        jTextFieldDataPedido1.setText("");
        jTextFieldCodigoCliente.requestFocus();
        count = 0;
        setBotoes(true, true, false, false, false, true);
    }
    
    public void tabelaPedidos () {
        try {
            pedDao = new PedidosDao();
            String sql = "select * from pedidos inner join clientes on clientes.codCliente = pedidos.Clientes_codCliente;";
            PreparedStatement stmt = pedDao.c.prepareStatement(sql);
            rs = stmt.executeQuery();
        } catch (SQLException | ClassNotFoundException error) {
            JOptionPane.showMessageDialog(null, "Problemas na conexão!\n" + error.toString());
        }
    }
    
    public void atualizarCampos() {
        pedDao.pedido.setCodPed(Integer.parseInt(jTextFieldId.getText()));
        if (pedDao.localizar()) {
           // Clientes - Pedidos
           jTextFieldId.setText(Integer.toString(pedDao.pedido.getCodPed()));
           jTextFieldCodigoCliente.setText(Integer.toString(pedDao.pedido.getCodCliente()));
           jTextFieldDataPedido.setText(converterData(pedDao.pedido.getData().toString()));
           // Cliente
           jTextFieldNome1.setText(pedDao.cliente.getNome());
           jTextFieldEndereco1.setText(pedDao.cliente.getEndereco());
           jTextFieldBairro1.setText(pedDao.cliente.getBairro());
           jTextFieldCidade1.setText(pedDao.cliente.getCidade());
           jTextFieldCep1.setText(pedDao.cliente.getCep());
           jTextFieldUf1.setText(pedDao.cliente.getUf());
           jTextFieldEmail1.setText(pedDao.cliente.getEmail());
           jTextFieldFone1.setText(pedDao.cliente.getFone());
           jTextFieldCelular1.setText(pedDao.cliente.getCelular());
           // Pedido
           jTextFieldDataPedido1.setText(converterData(pedDao.pedido.getData().toString()));
           setCamposTexto(true, true, false, false, false, false, false, false, false, false, false, false, false);
           setBotoes(true,true,false,true,true,true);
        } else {
            JOptionPane.showMessageDialog(null, "Pedido não encontrado!", "Falha na localização", JOptionPane.WARNING_MESSAGE);
            limparCampos();
        }
    }
    
    public String converterData (String data) {
        // 2023-06-13
        String ano = data.substring(0, 4); // 2023
        String mes = data.substring(5, 7); // 06
        String dia = data.substring(8, 10); // 13
        String r = dia + "/" + mes + "/" + ano; // 13/06/2023
        return r;
    }
    
    public void carregaDados() {
        try {
            if (rs.isAfterLast()) {
                rs.last();
            } else if (rs.isBeforeFirst()) {
                rs.first();
            }
            // Pedidos - Clientes
            jTextFieldId.setText(Integer.toString(rs.getInt("codPed")));
            jTextFieldCodigoCliente.setText(Integer.toString(rs.getInt("Clientes_codCliente")));
            jTextFieldDataPedido.setText(converterData(rs.getDate("data").toString()));
            // Clientes
            jTextFieldNome1.setText(rs.getString("nome"));
            jTextFieldEndereco1.setText(rs.getString("ender"));
            jTextFieldBairro1.setText(rs.getString("bairro"));
            jTextFieldCidade1.setText(rs.getString("cidade"));
            jTextFieldCep1.setText(rs.getString("cep"));
            jTextFieldUf1.setText(rs.getString("uf"));
            jTextFieldEmail1.setText(rs.getString("email"));
            jTextFieldFone1.setText(rs.getString("fone"));
            jTextFieldCelular1.setText(rs.getString("celular"));
            // Pedido
            jTextFieldDataPedido1.setText(converterData(rs.getDate("data").toString()));
            setBotoes(true,true,false,true,true,true);
            setCamposTexto (true, true, false, false, false, false, false, false, false, false, false, false, false);
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "Erro na conexão!\n" + error.toString());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonAvancarRegistro;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFimRegistros;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonInicioRegistros;
    private javax.swing.JButton jButtonLocalizar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonRetrocederRegistro;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonTelaInicial;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelBairro1;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelCelular1;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelCidade1;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelCodigoCliente;
    private javax.swing.JLabel jLabelDataPedido;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEmail1;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelEndereco1;
    private javax.swing.JLabel jLabelFone;
    private javax.swing.JLabel jLabelFone1;
    private javax.swing.JLabel jLabelInserirNovoRegistro;
    private javax.swing.JLabel jLabelLocalizarPedido;
    private javax.swing.JLabel jLabelMovimentacaoRegistros;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNome1;
    private javax.swing.JLabel jLabelPedido;
    private javax.swing.JLabel jLabelPesquisaId;
    private javax.swing.JLabel jLabelRelacaoClientePedido;
    private javax.swing.JLabel jLabelUf;
    private javax.swing.JLabel jLabelUf1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldBairro1;
    private javax.swing.JTextField jTextFieldCelular;
    private javax.swing.JTextField jTextFieldCelular1;
    private javax.swing.JTextField jTextFieldCep;
    private javax.swing.JTextField jTextFieldCep1;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCidade1;
    private javax.swing.JTextField jTextFieldCodigoCliente;
    private javax.swing.JTextField jTextFieldDataPedido;
    private javax.swing.JTextField jTextFieldDataPedido1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEmail1;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldEndereco1;
    private javax.swing.JTextField jTextFieldFone;
    private javax.swing.JTextField jTextFieldFone1;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNome1;
    private javax.swing.JTextField jTextFieldUf;
    private javax.swing.JTextField jTextFieldUf1;
    // End of variables declaration//GEN-END:variables
}
