package avaliacao11.view;

import java.sql.*;
import java.text.*;
import avaliacao11.model.dao.ProdutosDao;
import javax.swing.JOptionPane;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

public final class CadastroProdutos extends javax.swing.JFrame {
    private ProdutosDao prodDao;
    private ResultSet rs;
    int count = 0;
    /**
     * Creates new form CadastroProdutos
     */
    public CadastroProdutos() {
        initComponents();
        limparCampos();
        tabelaProdutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelDescricao = new javax.swing.JLabel();
        jTextFieldDescricao = new javax.swing.JTextField();
        jLabelPreco = new javax.swing.JLabel();
        jTextFieldPreco = new javax.swing.JTextField();
        jLabelUnidade = new javax.swing.JLabel();
        jTextFieldUnidade = new javax.swing.JTextField();
        jLabelQuantidadeAtual = new javax.swing.JLabel();
        jLabelQuantidadeInicial = new javax.swing.JLabel();
        jLabelDataCadastro = new javax.swing.JLabel();
        jTextFieldDataCadastro = new javax.swing.JTextField();
        jTextFieldQuantidadeAtual = new javax.swing.JTextField();
        jTextFieldQuantidadeInicial = new javax.swing.JTextField();
        jLabelPesquisaId = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jButtonTelaInicial = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabelMovimentacaoRegistros = new javax.swing.JLabel();
        jButtonInicioRegistros = new javax.swing.JButton();
        jButtonFimRegistros = new javax.swing.JButton();
        jButtonRetrocederRegistro = new javax.swing.JButton();
        jButtonNovo = new javax.swing.JButton();
        jButtonAvancarRegistro = new javax.swing.JButton();
        jButtonLocalizar = new javax.swing.JButton();
        jButtonIncluir = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Produtos");
        setAutoRequestFocus(false);

        jLabelDescricao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDescricao.setText("Descrição:");

        jLabelPreco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPreco.setText("Preço:");

        jLabelUnidade.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelUnidade.setText("Unidade:");

        jLabelQuantidadeAtual.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelQuantidadeAtual.setText("Quantidade atual:");

        jLabelQuantidadeInicial.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelQuantidadeInicial.setText("Quantidade inicial:");
        jLabelQuantidadeInicial.setToolTipText("");

        jLabelDataCadastro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelDataCadastro.setText("Data de cadastro:");

        jTextFieldDataCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataCadastroActionPerformed(evt);
            }
        });

        jTextFieldQuantidadeAtual.setToolTipText("");

        jLabelPesquisaId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPesquisaId.setText("ID do produto: ");

        jTextFieldId.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });

        jButtonTelaInicial.setText("Tela Inicial");
        jButtonTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTelaInicialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabelPesquisaId)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonTelaInicial)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelDescricao)
                                            .addComponent(jLabelUnidade))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelPreco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDataCadastro)
                                    .addComponent(jLabelQuantidadeInicial)
                                    .addComponent(jLabelQuantidadeAtual))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldQuantidadeInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldQuantidadeAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButtonTelaInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPesquisaId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDescricao)
                        .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldQuantidadeInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelQuantidadeInicial))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPreco)
                            .addComponent(jLabelDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUnidade)
                            .addComponent(jLabelQuantidadeAtual)
                            .addComponent(jTextFieldQuantidadeAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45))
        );

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setToolTipText("");
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelMovimentacaoRegistros.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelMovimentacaoRegistros.setText("Movimentação de Registros:");

        jButtonInicioRegistros.setText("<<");
        jButtonInicioRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioRegistrosActionPerformed(evt);
            }
        });

        jButtonFimRegistros.setText(">>");
        jButtonFimRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFimRegistrosActionPerformed(evt);
            }
        });

        jButtonRetrocederRegistro.setText("<");
        jButtonRetrocederRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetrocederRegistroActionPerformed(evt);
            }
        });

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonAvancarRegistro.setText(">");
        jButtonAvancarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvancarRegistroActionPerformed(evt);
            }
        });

        jButtonLocalizar.setText("Localizar");
        jButtonLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLocalizarActionPerformed(evt);
            }
        });

        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });

        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButtonNovo)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLocalizar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonIncluir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAlterar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabelMovimentacaoRegistros)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInicioRegistros)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRetrocederRegistro)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButtonAvancarRegistro)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFimRegistros))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jButtonExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo)
                    .addComponent(jButtonLocalizar)
                    .addComponent(jButtonIncluir)
                    .addComponent(jButtonAlterar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonCancelar)
                    .addComponent(jButtonSair))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInicioRegistros)
                    .addComponent(jButtonRetrocederRegistro)
                    .addComponent(jButtonAvancarRegistro)
                    .addComponent(jButtonFimRegistros)
                    .addComponent(jLabelMovimentacaoRegistros))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDataCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataCadastroActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        prodDao.produto.setCodProd(Integer.parseInt(jTextFieldId.getText()));
        prodDao.produto.setDescricao(jTextFieldDescricao.getText());
        prodDao.produto.setPreco(Float.parseFloat(jTextFieldPreco.getText()));
        prodDao.produto.setUnidade(jTextFieldUnidade.getText());
        prodDao.produto.setQtdeInicial(Float.parseFloat(jTextFieldQuantidadeInicial.getText()));
        prodDao.produto.setQtdeAtual(Float.parseFloat(jTextFieldQuantidadeAtual.getText()));
        
        Date data = new Date();
        String dataString = jTextFieldDataCadastro.getText();
        SimpleDateFormat format = new SimpleDateFormat ("dd/MM/yyyy");
        
        try {
            data = format.parse(dataString);
            java.sql.Date dataSql = new java.sql.Date (data.getTime()); // A passagem do valor de timestamp obtido por getTime() ao construtor de java.sql.Date permite criar um objeto java.sql.Date com a mesma data e hora de um objeto do tipo Date 
            prodDao.produto.setDataCad(dataSql);
        } catch (ParseException error) {
           Logger.getLogger(CadastroProdutos.class.getName()).log(Level.SEVERE, null, error);
        }
        
        JOptionPane.showMessageDialog(null, prodDao.atualizar(ProdutosDao.ALTERACAO));
        limparCampos();
        tabelaProdutos();        
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonInicioRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioRegistrosActionPerformed
        try {
            rs.first();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        carregaDados();
    }//GEN-LAST:event_jButtonInicioRegistrosActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        prodDao = new ProdutosDao();
        
        if (jTextFieldDescricao.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "A descrição não pode ser nula!");
            jTextFieldDescricao.requestFocus();
        }
        if (jTextFieldPreco.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O preço não pode ser nulo!");
            jTextFieldPreco.requestFocus();
        }
        if (jTextFieldUnidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "A unidade não pode ser nula!");
            jTextFieldUnidade.requestFocus();
        }
        if (jTextFieldQuantidadeInicial.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "A quantidade inicial não pode ser nula!");
            jTextFieldQuantidadeInicial.requestFocus();
        }
        if (jTextFieldDataCadastro.getText().equals("")) {
           JOptionPane.showMessageDialog(null, "A data de cadastro não pode ser nula!");
           jTextFieldDataCadastro.requestFocus();
        }
        if (jTextFieldQuantidadeAtual.getText().equals("")) {
           JOptionPane.showMessageDialog(null, "A quantidade atual não pode ser nula!");
           jTextFieldQuantidadeAtual.requestFocus();
        }
        
        prodDao.produto.setDescricao(jTextFieldDescricao.getText());
        prodDao.produto.setPreco(Float.parseFloat(jTextFieldPreco.getText()));
        prodDao.produto.setUnidade(jTextFieldUnidade.getText());
        prodDao.produto.setQtdeInicial(Float.parseFloat(jTextFieldQuantidadeInicial.getText()));
        prodDao.produto.setQtdeAtual(Float.parseFloat(jTextFieldQuantidadeAtual.getText()));
        
        Date data = new Date();
        String dataString = jTextFieldDataCadastro.getText();
        SimpleDateFormat format = new SimpleDateFormat ("dd/MM/yyyy");
        
        try {
            data = format.parse(dataString);
            java.sql.Date dataSql = new java.sql.Date (data.getTime()); // A passagem do valor de timestamp obtido por getTime() ao construtor de java.sql.Date permite criar um objeto java.sql.Date com a mesma data e hora de um objeto do tipo Date 
            prodDao.produto.setDataCad(dataSql);
        } catch (ParseException error) {
           Logger.getLogger(CadastroProdutos.class.getName()).log(Level.SEVERE, null, error);
        }
        
        JOptionPane.showMessageDialog(null, prodDao.atualizar(ProdutosDao.INCLUSAO));
        limparCampos();
        tabelaProdutos();
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        prodDao.produto.setCodProd(Integer.parseInt(jTextFieldId.getText()));
        prodDao.localizar();
        
        int confirmacao = JOptionPane.showConfirmDialog(null, prodDao.produto.getDescricao(), "Excluir o produto?", JOptionPane.YES_NO_OPTION);
        if (confirmacao == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, prodDao.atualizar(ProdutosDao.EXCLUSAO));
        }
        limparCampos();
        tabelaProdutos();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIdActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        limparCampos();
        setBotoes(false, false, true, false, false, true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLocalizarActionPerformed
       prodDao = new ProdutosDao();
       
      if (count == 0) {
          jTextFieldId.setEditable(true);
          jTextFieldId.requestFocus();
          count ++;
      } else {
          atualizarCampos();
      }
    }//GEN-LAST:event_jButtonLocalizarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        limparCampos();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonRetrocederRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetrocederRegistroActionPerformed
        try {
            rs.previous();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        carregaDados();
    }//GEN-LAST:event_jButtonRetrocederRegistroActionPerformed

    private void jButtonAvancarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvancarRegistroActionPerformed
        try {
            rs.next();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        carregaDados();
    }//GEN-LAST:event_jButtonAvancarRegistroActionPerformed

    private void jButtonFimRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFimRegistrosActionPerformed
        try {
            rs.last();
        } catch (SQLException ex) {
            Logger.getLogger(CadastroProdutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        carregaDados();
    }//GEN-LAST:event_jButtonFimRegistrosActionPerformed

    private void jButtonTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTelaInicialActionPerformed
        setVisible(false);
        Menu menu = new Menu ();
        menu.setVisible(true);
    }//GEN-LAST:event_jButtonTelaInicialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProdutos().setVisible(true);
            }
        });
    }
    
    public void setBotoes (boolean buttonNovo, boolean buttonLocalizar, boolean buttonIncluir, boolean buttonAlterar, boolean buttonExcluir, boolean buttonCancelar) {
        jButtonNovo.setEnabled(buttonNovo);
        jButtonLocalizar.setEnabled(buttonLocalizar);
        jButtonIncluir.setEnabled(buttonIncluir);
        jButtonAlterar.setEnabled(buttonAlterar);
        jButtonExcluir.setEnabled(buttonExcluir);
        jButtonCancelar.setEnabled(buttonCancelar);
    }
    
    public void limparCampos() {
        jTextFieldId.setEditable(false);
        count = 0;
        jTextFieldId.setText("");
        jTextFieldDescricao.setText("");
        jTextFieldPreco.setText("");
        jTextFieldUnidade.setText("");
        jTextFieldQuantidadeInicial.setText("");
        jTextFieldDataCadastro.setText("");
        jTextFieldQuantidadeAtual.setText("");
        jTextFieldDescricao.requestFocus();
        setBotoes(true, true, false, false, false, true);
    }
    
     public void atualizarCampos() {
        prodDao.produto.setCodProd(Integer.parseInt(jTextFieldId.getText()));
        if (prodDao.localizar()) {
            jTextFieldId.setText(Integer.toString(prodDao.produto.getCodProd()));
            jTextFieldDescricao.setText(prodDao.produto.getDescricao());
            jTextFieldPreco.setText(Float.toString(prodDao.produto.getPreco()));
            jTextFieldUnidade.setText(prodDao.produto.getUnidade());
            jTextFieldQuantidadeInicial.setText(Float.toString(prodDao.produto.getQtdeInicial()));
            jTextFieldDataCadastro.setText(converterData(prodDao.produto.getDataCad().toString()));
            jTextFieldQuantidadeAtual.setText(Float.toString(prodDao.produto.getQtdeAtual()));
            setBotoes (false, true, false, true, true, true);
        } else {
            JOptionPane.showMessageDialog(null, "Produto não encontrado!", "Falha na localização", JOptionPane.WARNING_MESSAGE);
            limparCampos();
        }
    }
            
    public void tabelaProdutos() {
        try {
            prodDao = new ProdutosDao();
            String sql = "select * from produtos";
            PreparedStatement stmt = prodDao.c.prepareStatement(sql);
            rs = stmt.executeQuery();
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "Problemas na conexão!\n" + error.toString());
        }
    }
    
    public String converterData (String data) {
        // 2023-06-13
        String ano = data.substring(0, 4); // 2023
        String mes = data.substring(5, 7); // 06
        String dia = data.substring(8, 10); // 13
        String r = dia + "/" + mes + "/" + ano; // 13/06/2023
        return r;
    }
    
    public void carregaDados() {
        try {
            if (rs.isAfterLast()) {
                rs.last();
            }
            if (rs.isBeforeFirst()) {
                rs.first();
            }
            
            jTextFieldId.setText(Integer.toString(rs.getInt("codProd")));
            jTextFieldDescricao.setText(rs.getString("descricao"));
            jTextFieldPreco.setText(Float.toString(rs.getFloat("preco")));
            jTextFieldUnidade.setText(rs.getString("unidade"));
            jTextFieldQuantidadeInicial.setText(Float.toString(rs.getFloat("qtdeInicial")));
            jTextFieldDataCadastro.setText(converterData(rs.getDate("dataCad").toString()));
            jTextFieldQuantidadeAtual.setText(Float.toString(rs.getFloat("qtdeAtual")));
            setBotoes(true,true,false,true,true,true);
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(null, "Problemas na conexão!\n" + error.toString());
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonAvancarRegistro;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFimRegistros;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonInicioRegistros;
    private javax.swing.JButton jButtonLocalizar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonRetrocederRegistro;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonTelaInicial;
    private javax.swing.JLabel jLabelDataCadastro;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelMovimentacaoRegistros;
    private javax.swing.JLabel jLabelPesquisaId;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JLabel jLabelQuantidadeAtual;
    private javax.swing.JLabel jLabelQuantidadeInicial;
    private javax.swing.JLabel jLabelUnidade;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldDataCadastro;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldPreco;
    private javax.swing.JTextField jTextFieldQuantidadeAtual;
    private javax.swing.JTextField jTextFieldQuantidadeInicial;
    private javax.swing.JTextField jTextFieldUnidade;
    // End of variables declaration//GEN-END:variables
}
